### PR TITLE
Get monitor configuration on osx

### PR DESCRIPTION
**Pull request by taboulot**
Use AppKit for getting monitor configuration on OSX

Closes #8

### CODE REVIEW

**Comment by taboulot** [comment]
Hi @Evidlo 

This PR is related to #8 

Never really developed in python ... Did my best 🙂

Hope you'll like it. It works just fine for me now.

**Comment by taboulot** [comment]
This solution is temporary while waiting to find time for fixing it directly in screeninfo.

**Comment by Evidlo** [comment]
Shouldn't this PR go to screeninfo?

**Comment by Evidlo** [comment]
Oh, I didn't see your last comment.  Thanks for the work put in so far, but I think we should wait until your changes get merged into screeninfo.

**Comment by taboulot** [comment]
Yes you right. It can be used by people as example for the moment.

**Comment by Evidlo** [comment]
This should be fixed when https://github.com/rr-/screeninfo/pull/42 is merged, so closing this for now.

**Pull request closed without merging**
