### PR TITLE
Fixed mouse spamming and  added a proper mouse hold function.

### PR DESCRIPTION
**Pull request by antopilo**
Before the Click function was called every iteration of the while loop.
I added a filter to only click again if the pen has been lifted up. This allows for smooth dragging and an overall better exeperience. Just a simple bool "has_lifted" as been added :) Hope you will accept this pr

### CODE REVIEW

**Comment by Evidlo** [comment]
> I added a filter to only click again if the pen has been lifted up. 

This was already the behavior before your changes.  `Button.press` is only called if `state=LIFTED` is True, and `state` is set to `LIFTED` only when the pen pressure drops below the threshold.  The only difference here is that you fixed the release threshold to 100.

**Comment by Evidlo** [comment]
Also see https://github.com/Evidlo/remarkable_mouse/pull/7

**Comment by antopilo** [comment]
It seems that you did not test your program on windows as it is unusable on windows. It spams click on every frame and it's terrible. It might not work like that on linux but fine. :)

**Comment by Evidlo** [comment]
There are still some issues on Windows, which I think I've narrowed down to some kind of buffering problem with Paramiko.

**Pull request closed without merging**
